name: PHP CI with GitHub Actions

on:
  push:
    branches:
      - test-worflow

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Unit Tests
        run: ./vendor/bin/phpunit --testsuite Unit

      - name: Run Functional Tests
        run: ./vendor/bin/phpunit --testsuite Functional

      - name: Run Integration Tests
        run: ./vendor/bin/phpunit --testsuite Integration

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins CI/CD
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/buildWithParameters?token=$JENKINS_API_TOKEN" \
          --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
